- name: configure student host.
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install git
      win_chocolatey:
        name: git
        state: present
      tags: config

    - name: Install git
      win_chocolatey:
        name: unity
        version: '5.6.2'
        state: present
      tags: config
